---
name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  frontend-ci:
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
          always-auth: true
          scope: '@schubergphilis'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with NPM
        run: |
          echo "@schubergphilis:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GMTDI_TOKEN: ${{ secrets.GMTDI_TOKEN }}

      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GMTDI_TOKEN }}

      - name: Run Tests
        run: yarn lint

      - name: Build project
        run: yarn build
        env:
          GENERATE_SOURCEMAP: 'false'

      - name: Set version
        run: yarn version --patch --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package project
        run: yarn pack && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Commit updated version
        run: |
          git add .
          git commit -m "chore: bump version [skip ci]"
          git push
